Improve signing of certificate
PyAr/pyafipws pull request #118
Opened 2023-06-21 11:39 UTC by HanslettTheDev

## Summary

This pull requests aims to improve the work done in [#113](https://github.com/PyAr/pyafipws/pull/113). Updating the cryptography module, fixing the broken tests and libraries

## Checklist

- [x] Classes, Variables, function and methods logic  ok
- [x] Comments written explaining what the code does
- [x] Test coverage with pytest implemented

2023-06-30 04:05 UTC, NicolasSandoval requested changes
I left some possibilities for small structural changes. Good job @HanslettTheDev.

2023-06-30 04:05 UTC, NicolasSandoval commented on wsaa.py
I think creating a memory buffer for the signing process, including all the structure like `_lib` and `_ffi` could go with the rest of the code handled by python2. The handling of the certificates is fine, which is out of the conditional.

2023-06-30 04:05 UTC, NicolasSandoval commented on wsaa.py
> +        if sys.version.split(" ")[0][0:3] == "2.7":
Maybe you would only check the major version number.
Something like:
```suggestion
        MAJOR = 0 # first string element
        if sys.version[MAJOR] == "2":
```
or use the `version_info` method
```suggestion
        if sys.version_info.major == 2:
```

2023-06-30 04:05 UTC, NicolasSandoval commented on wsaa.py
> +                    return part.get_payload(decode=False)
Would you try here to remove the repeated code? You could use `else` to separate the python3 code. I think it's better to rename `output` to `p7` directly.

2023-06-30 04:05 UTC, NicolasSandoval commented on wsaa.py
> +            if filename == "smime.p7s":
One possibility to avoid the `m` and `s` problem is to use the `startswith` method.
For instance:
```suggestion
            if filename and filename.startswith("smime.p7"):
```

2023-07-03 05:56 UTC, HanslettTheDev commented on wsaa.py
Done! Thanks

2023-07-03 05:59 UTC, HanslettTheDev commented on wsaa.py
> +                    return part.get_payload(decode=False)
Done! Changes made! This was a cool idea to reduce the repeated code. I was worried about this too

2023-07-03 23:11 UTC, closed without merging