Get all dependencies from the requirements.txt file
PyAr/pyafipws pull request #119
Opened 2023-06-21 12:02 UTC by HanslettTheDev

## Summary

This pull request solves this [Issue](https://github.com/PyAr/pyafipws/issues/105). The setup.py file has some other dependencies which setup.py has to be aware of so as to build the project. This PR solves that issue

## Checklist

- [X] Classes, Variables, function and methods logic  ok
- [X] Comments written explaining what the code does
- [X] All python code is PEP8 compliant (run black .)

2023-07-22 19:01 UTC, reingart requested changes
Hi @HanslettTheDev , sorry I missed this PR and I thought we already discussed this approach in #105

Just in case, here go my concerns / comments again:
* Dependencies should be explicitly declared in `install_requires`, with proper conditions for both python versions (changing `==` with `>=`  will not work for some dependencies like cryptography, minimal version with upper bound should be used)
* Instead of creating an ad-hoc custom script (get_dep.py), a generic one should be used, like [pip-tools](https://pypi.org/project/pip-tools/), so library versions could be resolved automatically in the future and manual pinning is avoided
* `requirements.txt` should not be used from `setup.py` (not a good practice), as it is the dependency freezing / locking for our tests but other projects that uses the library could need to use different library versions for compatibility

Python packaging documentation has more information about this topics and examples:
* https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#install-requires
* https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#install-requires-vs-requirements-files

2023-09-08 23:54 UTC, HanslettTheDev commented
Below is an image showing pip-compile being executed

![image](https://github.com/PyAr/pyafipws/assets/64011386/6b6f1fe2-aac7-4740-93e2-59e83354c006)

2023-09-13 01:30 UTC, reingart requested changes
Thanks! I left a couple of comments, maninly about windows dependencies that should be optional or just for development (compiling the executable for 3rd party languages)

2023-09-13 01:30 UTC, reingart commented on setup.py
> +        "py2exe==0.11.1.1;sys_platform == 'win32' and python_version > '3'"
py2exe should be a development dependency, not really needed for installation and normal operation

2023-09-13 01:30 UTC, reingart commented on setup.py
> +        "pywin32==304;sys_platform == 'win32' and python_version > '3'",
pywin32 should be an optional dependency, it is required to use this library from 3rd party languages (python apps don't need it)

2023-09-15 02:44 UTC, reingart approved these changes

2023-09-24 17:55 UTC, reingart requested changes

2023-09-24 17:55 UTC, reingart commented on setup.py
> +        "pysimplesoap @ git+https://github.com/pysimplesoap/pysimplesoap.git@py311#pysimplesoap;",
Here it is missing the python 3 conditional, right?
```suggestion
        "pysimplesoap @ git+https://github.com/pysimplesoap/pysimplesoap.git@py311#pysimplesoap; python_version > '3'",
```

2023-09-28 05:25 UTC, HanslettTheDev commented on setup.py
> +        "pysimplesoap @ git+https://github.com/pysimplesoap/pysimplesoap.git@py311#pysimplesoap;",
done

2023-10-01 03:27 UTC, reingart commented
Hi @HanslettTheDev , it seems there is an error in the requirements format, can you check it?
```
error in PyAfipWs setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at ""> '3'"": Expected stringEnd
Error: Process completed with exit code 1.
```
Probably we should publish the pysimplesoap package and use it instead of the github repo

2023-10-01 04:32 UTC, HanslettTheDev commented
> Hi @HanslettTheDev , it seems there is an error in the requirements format, can you check it?
> 
> ```
> error in PyAfipWs setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at ""> '3'"": Expected stringEnd
> Error: Process completed with exit code 1.
> ```
> 
> Probably we should publish the pysimplesoap package and use it instead of the github repo

I'll remove the markers for the pysimplesoap and then we merge. I'll open another ticket to solve the pysimplesoap just to be sure there are no extra dependencies that could fail along the way

2023-10-06 17:45 UTC, reingart approved these changes

2023-10-06 17:46 UTC, merged